sudo: false
os: linux
dist: trusty

language: java

jdk:
  - oraclejdk8

install: ./mvnw install -DskipTests=true -Dmaven.javadoc.skip=true -Dgpg.skip=true -B -V
script: ./mvnw verify -Dgpg.skip=true
